org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.java.home=C:\\Users\\Administrator\\tools\\jdk-17
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=false
systemProp.java.net.preferIPv4Stack=true
systemProp.org.gradle.internal.http.connectionTimeout=20000
systemProp.org.gradle.internal.http.socketTimeout=20000
kotlin.code.style=official
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
